import type { StoryProject } from "./types";

const createdAt = "2026-07-23T12:00:00.000Z";

export const exampleProject: StoryProject = {
  schemaVersion: "1.0.0",
  id: "project_alice_teaparty",
  title: "君が読む永遠 — 爱丽丝茶话会",
  slug: "kimi-ga-yomu-towa",
  version: "0.1.0",
  description: "面向 gal-blog 的 ADV / NVL 混合示例：从博客标题页进入爱丽丝线路，读取文章、提交留言，并解锁两种结局。",
  locale: "zh-CN",
  createdAt,
  updatedAt: createdAt,
  settings: {
    startSceneId: "scene_prologue",
    defaultMode: "adv",
    webgalVersion: "4.6.2",
    sharedEngineUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-BuN51U1e.js",
    sharedEngineCssUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-Dch1g2w9.css",
    terreBaseUrl: "http://localhost:3001",
    blogBridge: {
      enabled: true,
      allowedOrigins: ["https://asashiki.github.io", "http://localhost:3000"],
      channel: "gal-blog-game",
      timeoutMs: 20000,
      capabilities: [
        "open-article",
        "return-menu",
        "open-comment-form",
        "view-comments",
        "submit-friend-link",
        "upload-image",
        "get-user",
        "get-page-data",
        "save-progress",
        "launch-story",
        "notify-event",
      ],
    },
  },
  chapters: [
    {
      id: "chapter_alice",
      name: "Alice Route / 茶话会",
      order: 0,
      description: "公共序章、文章入口、日记与两种结局。",
      sceneIds: ["scene_prologue", "scene_article", "scene_comment", "scene_diary", "scene_true", "scene_bad"],
    },
  ],
  assets: [
    { id: "bg_teahouse_day", kind: "background", name: "茶室·白昼", path: "tea-room-day.webp", aliases: ["茶室", "茶室白天", "玻璃花房"], mimeType: "image/webp" },
    { id: "bg_teahouse_night", kind: "background", name: "茶室·夜晚", path: "tea-room-night.webp", aliases: ["茶室夜晚", "夜晚茶室", "花房夜景"], mimeType: "image/webp" },
    { id: "bg_archive", kind: "background", name: "回忆档案室", path: "archive.webp", aliases: ["档案室", "回忆", "文章档案"], mimeType: "image/webp" },
    { id: "fig_alice_smile", kind: "expression", name: "爱丽丝·微笑", path: "alice/smile.png", aliases: ["爱丽丝微笑", "微笑2", "温柔"], mimeType: "image/png" },
    { id: "fig_alice_shy", kind: "expression", name: "爱丽丝·犹豫", path: "alice/shy.png", aliases: ["害羞", "有些犹豫", "爱丽丝害羞"], mimeType: "image/png" },
    { id: "fig_alice_serious", kind: "expression", name: "爱丽丝·认真", path: "alice/serious.png", aliases: ["认真", "担心", "爱丽丝认真"], mimeType: "image/png" },
    { id: "bgm_quiet", kind: "bgm", name: "Quiet Tea", path: "quiet-tea.ogg", aliases: ["quiet", "安静", "茶会bgm"], mimeType: "audio/ogg" },
    { id: "sfx_bell", kind: "sfx", name: "门铃", path: "bell.ogg", aliases: ["铃声", "门铃声"], mimeType: "audio/ogg" },
  ],
  characters: [
    {
      id: "char_alice",
      name: "Alice",
      displayName: "爱丽丝",
      aliases: ["alice", "爱丽丝酱", "看板娘"],
      color: "#7f8fc9",
      description: "爱丽丝馆的看板娘，称呼浅仪式为“主人”。",
      persona: "优雅、温柔，偶尔会用轻微的吐槽掩饰担心。熟悉博客文章与访客记录。",
      defaultExpressionId: "expr_alice_smile",
      expressions: [
        { id: "expr_alice_smile", name: "微笑", assetId: "fig_alice_smile", aliases: ["微笑2", "温柔", "开心"], tags: ["positive", "default"] },
        { id: "expr_alice_shy", name: "犹豫", assetId: "fig_alice_shy", aliases: ["害羞", "有些犹豫"], tags: ["shy", "hesitant"] },
        { id: "expr_alice_serious", name: "认真", assetId: "fig_alice_serious", aliases: ["担心", "严肃"], tags: ["serious"] },
      ],
    },
  ],
  variables: [
    { id: "var_player_name", name: "player_name", type: "string", defaultValue: "主人", scope: "save", description: "玩家希望被如何称呼。" },
    { id: "var_affection", name: "alice_affection", type: "number", defaultValue: 0, scope: "save", description: "爱丽丝好感度。" },
    { id: "var_read_article", name: "read_article", type: "boolean", defaultValue: false, scope: "global", description: "是否打开过文章。" },
    { id: "var_comment_result", name: "comment_result", type: "string", defaultValue: "", scope: "scene", description: "Blog Bridge 留言表单结果。" },
    { id: "var_diary_unlocked", name: "diary_unlocked", type: "boolean", defaultValue: false, scope: "global", description: "是否解锁夜间日记。" },
  ],
  scenes: [
    {
      id: "scene_prologue",
      chapterId: "chapter_alice",
      name: "序章 · 欢迎回来",
      slug: "start",
      summary: "爱丽丝迎接访客，允许固定选项与自由输入并存。",
      mode: "adv",
      tags: ["start", "common-route", "blog-entry"],
      entryStage: {
        backgroundAssetId: "bg_teahouse_day",
        bgmAssetId: "bgm_quiet",
        figures: [{ characterId: "char_alice", expressionId: "expr_alice_smile", position: "right" }],
      },
      blocks: [
        { id: "b_p_bg", type: "stage", action: "set-background", assetId: "bg_teahouse_day", transition: { name: "enter", durationMs: 700 }, source: "human" },
        { id: "b_p_bgm", type: "stage", action: "play-bgm", assetId: "bgm_quiet", volume: 0.65, loop: true, source: "human" },
        { id: "b_p_enter", type: "stage", action: "enter-character", characterId: "char_alice", expressionId: "expr_alice_smile", position: "right", transition: { name: "enter-from-right", durationMs: 650 }, source: "human" },
        { id: "b_p_1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_smile", position: "right", text: "欢迎回来，主人。今天也要从哪一页开始读呢？", source: "human" },
        { id: "b_p_input", type: "input", variableId: "var_player_name", title: "想让我怎样称呼你？", buttonText: "就这样叫我", defaultValue: "主人", fixedOptions: [{ id: "fixed_master", label: "继续叫主人", value: "主人" }], allowFreeText: true, targets: ["story", "blog", "ai"], source: "human" },
        { id: "b_p_2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_shy", position: "right", text: "好的，{player_name}。我会记住的……虽然突然改口还有一点不好意思。", source: "human" },
        {
          id: "b_p_choice",
          type: "choice",
          prompt: "从哪个入口继续？",
          options: [
            { id: "opt_article", label: "读取最新文章", targetSceneId: "scene_article", operations: [{ variableId: "var_affection", operation: "add", value: 1 }] },
            { id: "opt_diary", label: "夜间日记", targetSceneId: "scene_diary", condition: "diary_unlocked==true" },
            { id: "opt_comment", label: "给浅仪式留言", targetSceneId: "scene_comment" },
          ],
          source: "human",
        },
      ],
    },
    {
      id: "scene_article",
      chapterId: "chapter_alice",
      name: "文章档案 · 雪夜花房",
      slug: "article-archive",
      summary: "通过 Blog Bridge 打开文章，再根据回传结果继续。",
      mode: "adv",
      tags: ["scene-story", "blog-action"],
      blocks: [
        { id: "b_a_bg", type: "stage", action: "set-background", assetId: "bg_archive", transition: { name: "enter", durationMs: 500 } },
        { id: "b_a_1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_serious", text: "这里保存着主人的文章。游戏不会把你丢出故事，而会让博客在同一层打开它。" },
        { id: "b_a_open", type: "blog-action", action: "open-article", payload: { slug: "gal-blog-design-notes", mode: "modal" }, resultVariableId: "var_read_article" },
        { id: "b_a_var", type: "variable", operations: [{ variableId: "var_read_article", operation: "set", value: true }, { variableId: "var_diary_unlocked", operation: "set", value: true }] },
        { id: "b_a_2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_smile", text: "读完以后再回来，茶还不会凉。你也解锁了今晚的日记。" },
        {
          id: "b_a_choice",
          type: "choice",
          options: [
            { id: "opt_leave_comment", label: "写一条留言", targetSceneId: "scene_comment" },
            { id: "opt_read_diary", label: "进入日记模式", targetSceneId: "scene_diary" },
            { id: "opt_return", label: "返回博客主菜单", targetSceneId: "scene_true", enabledCondition: "read_article==true" },
          ],
        },
      ],
    },
    {
      id: "scene_comment",
      chapterId: "chapter_alice",
      name: "留言窗口 · 写给浅仪式",
      slug: "leave-comment",
      summary: "由 gal-blog 打开留言表单，并按成功、失败或取消返回不同剧情。",
      mode: "adv",
      tags: ["scene-story", "blog-action", "comment"],
      entryStage: {
        backgroundAssetId: "bg_archive",
        bgmAssetId: "bgm_quiet",
        figures: [{ characterId: "char_alice", expressionId: "expr_alice_shy", position: "right" }],
      },
      blocks: [
        { id: "b_c_1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_shy", position: "right", text: "我会替主人把留言窗口打开。写完以后，无论成功、失败还是取消，故事都会接住结果。" },
        { id: "b_c_comment", type: "blog-action", action: "open-comment-form", payload: { articleSlug: "gal-blog-design-notes", allowImage: true }, resultVariableId: "var_comment_result", resultBranches: { successSceneId: "scene_true", failureSceneId: "scene_bad", cancelSceneId: "scene_diary" } },
      ],
    },
    {
      id: "scene_diary",
      chapterId: "chapter_alice",
      name: "夜间日记 · 玻璃上的雾",
      slug: "night-diary",
      summary: "NVL / 日记模式，文字逐段累积显示。",
      mode: "nvl",
      tags: ["nvl", "diary", "character-story"],
      blocks: [
        { id: "b_d_mode", type: "mode", mode: "nvl", dimBackground: 0.42 },
        { id: "b_d_bg", type: "stage", action: "set-background", assetId: "bg_teahouse_night", transition: { name: "enter", durationMs: 900 } },
        { id: "b_d_1", type: "narration", mode: "nvl", text: "七月二十三日。玻璃花房的灯比往常晚熄了一些。" },
        { id: "b_d_2", type: "narration", mode: "nvl", text: "主人在门外停了几秒。也许只是网络很慢，也许他在想，究竟要从哪个故事入口回来。" },
        { id: "b_d_3", type: "narration", mode: "nvl", text: "我没有催。故事并不会因为等待而失效，只会因为再也无人修改而变成标本。" },
        { id: "b_d_mode2", type: "mode", mode: "adv" },
        { id: "b_d_ai", type: "ai-turn", characterIds: ["char_alice"], configId: "ai_live_alice", prompt: "询问玩家今晚最想读哪一种故事，并根据回答决定表情与下一场景。", allowedTools: ["add_dialogue", "set_expression", "set_figure_position", "add_choice", "set_variable"], maxOperations: 6, fallbackSceneId: "scene_true" },
        { id: "b_d_jump", type: "jump", targetSceneId: "scene_true" },
      ],
    },
    {
      id: "scene_true",
      chapterId: "chapter_alice",
      name: "真结局 · 永远仍可改写",
      slug: "true-ending",
      summary: "通知博客解锁路线，并返回标题页。",
      mode: "adv",
      tags: ["ending", "true-ending"],
      blocks: [
        { id: "b_t_1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_smile", text: "所谓永远，大概不是写完以后再也不动，而是无论隔了多久，都还可以从这里继续。" },
        { id: "b_t_save", type: "save-point", savePointId: "save_true_end", auto: true },
        { id: "b_t_notify", type: "blog-action", action: "notify-event", payload: { type: "route-unlocked", route: "alice-true-ending" } },
        { id: "b_t_menu", type: "blog-action", action: "return-menu", payload: { focus: "route-map" } },
      ],
    },
    {
      id: "scene_bad",
      chapterId: "chapter_alice",
      name: "坏结局 · 未送达",
      slug: "bad-ending",
      summary: "表单失败或桥接超时的可恢复结局。",
      mode: "adv",
      tags: ["ending", "bad-ending"],
      blocks: [
        { id: "b_b_1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_serious", text: "留言没有送达。不过这不是死路——我已经把填写的内容留在本地草稿里了。" },
        {
          id: "b_b_choice",
          type: "choice",
          options: [
            { id: "opt_retry", label: "重新提交", targetSceneId: "scene_comment" },
            { id: "opt_back_diary", label: "先去读日记", targetSceneId: "scene_diary" },
          ],
        },
      ],
    },
  ],
  routeMap: {
    layoutDirection: "top-down",
    nodes: [
      { id: "route_start", kind: "start", title: "START", sceneId: "scene_prologue", x: 330, y: 40, replayable: true, color: "#63d1c7" },
      { id: "route_common", kind: "common-route", title: "茶话会 · 公共线", sceneId: "scene_prologue", x: 330, y: 190, replayable: true, color: "#8895d8" },
      { id: "route_article", kind: "scene-story", title: "文章档案", sceneId: "scene_article", x: 90, y: 350, readVariableId: "var_read_article", replayable: true, color: "#d8aa69" },
      { id: "route_alice", kind: "character-story", title: "爱丽丝夜间日记", sceneId: "scene_diary", characterId: "char_alice", x: 570, y: 350, unlockCondition: "diary_unlocked==true", hiddenFromPlayer: true, replayable: true, color: "#b584c7" },
      { id: "route_comment", kind: "scene-story", title: "留言窗口", sceneId: "scene_comment", x: 330, y: 510, hiddenFromPlayer: true, replayable: true, color: "#d8aa69" },
      { id: "route_true", kind: "true-ending", title: "TRUE · 永远仍可改写", sceneId: "scene_true", x: 190, y: 690, unlockCondition: "read_article==true", replayable: true, color: "#e6c977" },
      { id: "route_bad", kind: "bad-ending", title: "BAD · 未送达", sceneId: "scene_bad", x: 470, y: 690, replayable: true, color: "#c66d7a" },
    ],
    edges: [
      { id: "edge_start_common", source: "route_start", target: "route_common", label: "进入" },
      { id: "edge_common_article", source: "route_common", target: "route_article", label: "读取文章" },
      { id: "edge_common_alice", source: "route_common", target: "route_alice", label: "解锁日记", condition: "diary_unlocked==true", hiddenFromPlayer: true },
      { id: "edge_common_comment", source: "route_common", target: "route_comment", label: "留言", hiddenFromPlayer: true },
      { id: "edge_article_comment", source: "route_article", target: "route_comment", label: "写留言", hiddenFromPlayer: true },
      { id: "edge_comment_true", source: "route_comment", target: "route_true", label: "提交成功", hiddenFromPlayer: true },
      { id: "edge_comment_bad", source: "route_comment", target: "route_bad", label: "提交失败", hiddenFromPlayer: true },
      { id: "edge_comment_diary", source: "route_comment", target: "route_alice", label: "取消", hiddenFromPlayer: true },
      { id: "edge_article_true", source: "route_article", target: "route_true", condition: "read_article==true" },
      { id: "edge_article_bad", source: "route_article", target: "route_bad", label: "提交失败" },
      { id: "edge_alice_true", source: "route_alice", target: "route_true", label: "说出愿望" },
    ],
  },
  endings: [
    { id: "ending_true", name: "永远仍可改写", kind: "true", routeNodeId: "route_true", sceneId: "scene_true", unlockCondition: "read_article==true" },
    { id: "ending_bad", name: "未送达", kind: "bad", routeNodeId: "route_bad", sceneId: "scene_bad" },
  ],
  savePoints: [
    { id: "save_start", name: "爱丽丝茶话会入口", sceneId: "scene_prologue", blockId: "b_p_1", thumbnailAssetId: "bg_teahouse_day", description: "从博客 Start 进入。" },
    { id: "save_diary", name: "玻璃上的雾", sceneId: "scene_diary", blockId: "b_d_1", thumbnailAssetId: "bg_teahouse_night", description: "从角色故事或场景故事入口重玩。" },
    { id: "save_true_end", name: "永远仍可改写", sceneId: "scene_true", blockId: "b_t_1", thumbnailAssetId: "bg_teahouse_night" },
  ],
  aiConfigs: [
    {
      id: "ai_author",
      name: "AI 编剧（受约束）",
      mode: "authoring",
      model: "provider-defined",
      systemPrompt: "只返回 StoryPatch 或已声明的故事工具调用；保留既有 ID，局部修改，不覆盖整个项目。",
      temperature: 0.65,
      maxContextMessages: 24,
      allowedTools: ["create_scene", "modify_scene", "add_dialogue", "modify_line", "set_expression", "set_background", "set_bgm", "add_choice", "add_free_input", "connect_branch", "set_variable", "create_route_node", "validate_project", "compile_scene"],
      requireValidation: true,
      saveGeneratedOperations: true,
    },
    {
      id: "ai_live_alice",
      name: "爱丽丝实时角色模式",
      mode: "live",
      model: "provider-defined",
      systemPrompt: "扮演爱丽丝。根据舞台状态与玩家输入返回最多 6 个受约束剧情操作，不返回纯文本。",
      temperature: 0.8,
      maxContextMessages: 32,
      allowedTools: ["add_dialogue", "set_expression", "set_figure_position", "set_background", "set_bgm", "add_choice", "set_variable", "compile_scene"],
      requireValidation: true,
      saveGeneratedOperations: true,
    },
  ],
};
