import type { StoryProject } from "./types";
import { figureShotTransform } from "./figureFraming";

const createdAt = "2026-07-26T15:30:00.000Z";

/**
 * The starter project intentionally contains only the three files supplied by
 * the user. There are no placeholder backgrounds, music tracks, voices, sound
 * effects, or expression files hiding behind metadata-only registrations.
 */
export const exampleProject: StoryProject = {
  schemaVersion: "1.0.0",
  id: "project_alice_minimal",
  title: "爱丽丝茶室 · WebGAL 实机验收样章",
  slug: "alice-tea-room",
  version: "0.4.0",
  description: "使用三份真实素材手工编写的 WebGAL 验收样章；它用于检查实机画面，不冒充 AI 生成结果。",
  locale: "zh-CN",
  createdAt,
  updatedAt: createdAt,
  settings: {
    startSceneId: "scene_return",
    defaultMode: "adv",
    webgalVersion: "4.6.2",
    sharedEngineUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-BuN51U1e.js",
    sharedEngineCssUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-Dch1g2w9.css",
    blogBridge: {
      enabled: false,
      allowedOrigins: [],
      channel: "gal-blog-game",
      timeoutMs: 20000,
      capabilities: [],
    },
  },
  chapters: [
    {
      id: "chapter_one",
      name: "第一章 · 午后茶室",
      order: 0,
      description: "五个连续片段共享同一舞台，验证片段切换不会破坏游戏的连续感。",
      sceneIds: ["scene_return", "scene_teatime", "scene_questions", "scene_protest", "scene_bookmark"],
    },
  ],
  assets: [
    {
      id: "bg_alice_tea_room_day",
      kind: "background",
      name: "爱丽丝馆 · 白昼茶室",
      path: "project-assets/alice-tea-room-day.png",
      aliases: ["白昼茶室", "爱丽丝茶室", "玻璃花房", "茶会房间"],
      mimeType: "image/png",
      metadata: {
        description: "明亮的欧式玻璃茶室与图书空间，窗外是白昼花园，中央摆有茶桌。",
        recommendedUse: "白天的茶会、迎接、日常对话与安静室内场景；当前没有夜晚版本。",
        tags: "茶室, 白天, 室内, 花园, 安静, 温暖",
        originalName: "ChatGPT Image 2026年7月16日 01_46_33.png",
        semanticReady: true,
        bundled: true,
      },
    },
    {
      id: "fig_alice_standard_normal",
      kind: "expression",
      name: "爱丽丝 · 标准立绘 / 平静微笑",
      path: "project-assets/alice-standard-normal.png",
      aliases: ["爱丽丝标准立绘", "爱丽丝普通", "爱丽丝微笑", "Alice_0"],
      mimeType: "image/png",
      metadata: {
        description: "爱丽丝的标准全身立绘，神态平静并带有轻微微笑，右手靠近胸前。",
        recommendedUse: "普通对话、迎接、温和回应与较正式的茶会场景。",
        tags: "爱丽丝, 标准立绘, 平静, 轻微微笑, 全身",
        originalName: "Alice_0.png",
        figureShot: "waist",
        figureDefaultPosition: "right",
        figureDefaultX: 0,
        figureDefaultY: 570,
        figureDefaultScale: 1.82,
        sourceWidth: 1086,
        sourceHeight: 1449,
        figureVisibleLeft: 0.2284,
        figureVisibleTop: 0.0069,
        figureVisibleRight: 0.7956,
        figureVisibleBottom: 0.96,
        semanticReady: true,
        bundled: true,
      },
    },
    {
      id: "fig_alice_chibi_normal",
      kind: "expression",
      name: "爱丽丝 · Q版立绘 / 平静",
      path: "project-assets/alice-chibi-normal.png",
      aliases: ["爱丽丝Q版", "爱丽丝小人", "chibi Alice", "alice-chibi normal"],
      mimeType: "image/png",
      metadata: {
        description: "爱丽丝的 Q 版全身立绘，闭嘴、平静直视，适合轻松或强调可爱感的演出。",
        recommendedUse: "轻松回应、提示、短小过场或带一点喜剧感的场景；不作为强烈情绪差分。",
        tags: "爱丽丝, Q版, 平静, 可爱, 全身",
        originalName: "alice-chibi_normal.png",
        figureShot: "full",
        figureDefaultPosition: "center",
        figureDefaultX: 0,
        figureDefaultY: 34,
        figureDefaultScale: 0.94,
        sourceWidth: 1024,
        sourceHeight: 1536,
        figureVisibleLeft: 0.0596,
        figureVisibleTop: 0.099,
        figureVisibleRight: 0.9404,
        figureVisibleBottom: 0.9603,
        semanticReady: true,
        bundled: true,
      },
    },
  ],
  characters: [
    {
      id: "char_alice",
      name: "Alice",
      displayName: "爱丽丝",
      aliases: ["alice", "看板娘"],
      color: "#6576b7",
      description: "爱丽丝馆的看板娘，称呼浅仪式为“主人”。",
      persona: "语气温柔、克制而礼貌。当前只登记了标准立绘与 Q 版立绘，不虚构其他表情。",
      defaultExpressionId: "expr_alice_standard_normal",
      expressions: [
        {
          id: "expr_alice_standard_normal",
          name: "标准立绘 · 平静微笑",
          assetId: "fig_alice_standard_normal",
          aliases: ["普通", "平静", "微笑", "标准"],
          tags: ["default", "calm", "soft-smile"],
        },
        {
          id: "expr_alice_chibi_normal",
          name: "Q版立绘 · 平静",
          assetId: "fig_alice_chibi_normal",
          aliases: ["Q版", "小人", "可爱", "平静"],
          tags: ["chibi", "calm", "cute"],
        },
      ],
    },
  ],
  variables: [],
  scenes: [
    {
      id: "scene_return",
      chapterId: "chapter_one",
      name: "01 · 午后的归来",
      slug: "return",
      summary: "主人回到爱丽丝馆，爱丽丝在茶室迎接；舞台只在这里初始化，后续片段连续衔接。",
      aiContext: "白昼茶室。爱丽丝以腰上构图站在画面右侧，温柔迎接刚回来的主人，不使用不存在的表情或 BGM。",
      mode: "adv",
      tags: ["start", "hand-authored-acceptance"],
      entryStage: {
        backgroundAssetId: "bg_alice_tea_room_day",
        figures: [{
          characterId: "char_alice",
          expressionId: "expr_alice_standard_normal",
          position: "right",
          transform: figureShotTransform("waist"),
        }],
      },
      blocks: [
        { id: "return_bg", type: "stage", action: "set-background", assetId: "bg_alice_tea_room_day", transition: { name: "enter", durationMs: 900 }, source: "human" },
        { id: "return_alice", type: "stage", action: "enter-character", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", transition: { name: "enter-from-right", durationMs: 700 }, source: "human" },
        { id: "return_n1", type: "narration", text: "推开玻璃门时，午后的光正好落在茶桌边缘。", source: "human" },
        { id: "return_d1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "欢迎回来，主人。外面比想象中更热吧？", source: "human" },
        { id: "return_d2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "我把窗边的位置留了下来，也提前晾好了红茶。", source: "human" },
        { id: "return_n2", type: "narration", text: "她没有催促，只把椅子轻轻向后拉开了一点。", source: "human" },
        { id: "return_d3", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "今天的事情，可以坐下以后慢慢说。", source: "human" },
        { id: "return_next", type: "jump", targetSceneId: "scene_teatime", source: "human" },
      ],
    },
    {
      id: "scene_teatime",
      chapterId: "chapter_one",
      name: "02 · 窗边的茶会",
      slug: "teatime",
      summary: "场景和立绘保持不变，片段切换不重新入场；玩家选择先喝茶还是先看书。",
      aiContext: "沿用上一段的白昼茶室和爱丽丝标准立绘。用一个自然选择推进茶会，两条回答最后汇合。",
      mode: "adv",
      tags: ["choice", "continuous-stage"],
      entryStage: {
        backgroundAssetId: "bg_alice_tea_room_day",
        figures: [{
          characterId: "char_alice",
          expressionId: "expr_alice_standard_normal",
          position: "right",
          transform: figureShotTransform("waist"),
        }],
      },
      blocks: [
        { id: "tea_n1", type: "narration", text: "瓷杯落在碟子上，发出很轻的一声。", source: "human" },
        { id: "tea_d1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "红茶还需要一点时间。主人想先做什么？", source: "human" },
        {
          id: "tea_choice",
          type: "choice",
          prompt: "茶会开始前……",
          options: [
            { id: "tea_choose_drink", label: "先尝一口红茶", targetBlockId: "tea_drink" },
            { id: "tea_choose_book", label: "先看看桌上的书", targetBlockId: "tea_book" },
          ],
          source: "human",
        },
        { id: "tea_drink", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "小心烫。第一口不用急着评价，我还准备了第二壶。", source: "human" },
        { id: "tea_drink_next", type: "jump", targetBlockId: "tea_join", source: "human" },
        { id: "tea_book", type: "narration", text: "书页间夹着一枚浅蓝色的书签，停在上次读到的位置。", source: "human" },
        { id: "tea_book_d", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "我没有翻动它。主人留下的进度，当然要等主人回来。", source: "human" },
        { id: "tea_book_next", type: "jump", targetBlockId: "tea_join", source: "human" },
        { id: "tea_join", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "不过，在继续之前……我有几件小事想问。", source: "human" },
        { id: "tea_next", type: "jump", targetSceneId: "scene_questions", source: "human" },
      ],
    },
    {
      id: "scene_questions",
      chapterId: "chapter_one",
      name: "03 · 没说出口的问题",
      slug: "questions",
      summary: "一个片段内部包含可反复返回的对话菜单；外层地图只保留这一枚节点。",
      aiContext: "沿用舞台。设计一个可循环的内部话题菜单，玩家可以逐项询问，选择继续后才离开当前片段。",
      mode: "adv",
      tags: ["internal-loop", "continuous-stage"],
      entryStage: {
        backgroundAssetId: "bg_alice_tea_room_day",
        figures: [{
          characterId: "char_alice",
          expressionId: "expr_alice_standard_normal",
          position: "right",
          transform: figureShotTransform("waist"),
        }],
      },
      blocks: [
        { id: "questions_d1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "主人最近总是很晚才回来。虽然我不该追问得太多……", source: "human" },
        { id: "questions_d2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "至少，请让我知道该从哪里开始担心。", source: "human" },
        {
          id: "questions_menu",
          type: "choice",
          prompt: "想先回应哪一件事？",
          options: [
            { id: "questions_work", label: "解释最近在忙的工作", targetBlockId: "questions_work_answer" },
            { id: "questions_wait", label: "问她是不是一直在等", targetBlockId: "questions_wait_answer" },
            { id: "questions_continue", label: "答应以后会早点回来", targetBlockId: "questions_leave" },
          ],
          source: "human",
        },
        { id: "questions_work_answer", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "原来如此。工作本身没有错，只是主人也要记得把休息写进计划里。", source: "human" },
        { id: "questions_work_return", type: "jump", targetBlockId: "questions_menu", source: "human" },
        { id: "questions_wait_answer", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "……只是一小会儿。至少在钟声响过三次以前，都只能算一小会儿。", source: "human" },
        { id: "questions_wait_return", type: "jump", targetBlockId: "questions_menu", source: "human" },
        { id: "questions_leave", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "我记住了。主人亲口说过的话，我可是会认真保存的。", source: "human" },
        { id: "questions_next", type: "jump", targetSceneId: "scene_protest", source: "human" },
      ],
    },
    {
      id: "scene_protest",
      chapterId: "chapter_one",
      name: "04 · 小小的抗议",
      slug: "protest",
      summary: "Q 版立绘只作为短暂喜剧演出使用，并采用全身构图；不会把它当成普通表情替换。",
      aiContext: "短暂切换为 Q 版全身演出，强调爱丽丝一本正经的小抗议；随后恢复普通 ADV 立绘。",
      mode: "adv",
      tags: ["chibi-cut", "continuous-stage"],
      entryStage: {
        backgroundAssetId: "bg_alice_tea_room_day",
        figures: [{
          characterId: "char_alice",
          expressionId: "expr_alice_chibi_normal",
          position: "center",
          transform: figureShotTransform("full"),
        }],
      },
      blocks: [
        { id: "protest_chibi", type: "stage", action: "set-expression", characterId: "char_alice", expressionId: "expr_alice_chibi_normal", position: "center", transition: { name: "enter", durationMs: 320 }, source: "human" },
        { id: "protest_d1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_chibi_normal", position: "center", text: "还有一件事。", source: "human" },
        { id: "protest_d2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_chibi_normal", position: "center", text: "不可以把『我会早点回来』理解成『只比昨天早五分钟』。", source: "human" },
        { id: "protest_n1", type: "narration", text: "她用极其认真的语气，提出了一个几乎没有协商余地的补充条款。", source: "human" },
        { id: "protest_d3", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_chibi_normal", position: "center", text: "至少要早到足够一起喝完一壶茶。", source: "human" },
        { id: "protest_next", type: "jump", targetSceneId: "scene_bookmark", source: "human" },
      ],
    },
    {
      id: "scene_bookmark",
      chapterId: "chapter_one",
      name: "05 · 留给明天的书签",
      slug: "bookmark",
      summary: "恢复腰上标准立绘，在同一茶室自然收束样章。",
      aiContext: "恢复爱丽丝标准腰上立绘，安静地结束茶会。没有 BGM 就保持静音。",
      mode: "adv",
      tags: ["ending", "continuous-stage"],
      entryStage: {
        backgroundAssetId: "bg_alice_tea_room_day",
        figures: [{
          characterId: "char_alice",
          expressionId: "expr_alice_standard_normal",
          position: "right",
          transform: figureShotTransform("waist"),
        }],
      },
      blocks: [
        { id: "bookmark_standard", type: "stage", action: "set-expression", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", transition: { name: "enter-from-right", durationMs: 520 }, source: "human" },
        { id: "bookmark_n1", type: "narration", text: "窗外的光线慢慢偏向书架，杯中的红茶也只剩下最后一点余温。", source: "human" },
        { id: "bookmark_d1", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "今天就读到这里吧。", source: "human" },
        { id: "bookmark_d2", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "没说完的话、没看完的书，还有下一壶茶，都可以留给明天。", source: "human" },
        { id: "bookmark_n2", type: "narration", text: "爱丽丝把书签夹回原处，像是替这段午后保存了一个不会消失的入口。", source: "human" },
        { id: "bookmark_d3", type: "dialogue", characterId: "char_alice", expressionId: "expr_alice_standard_normal", position: "right", text: "晚些时候见，主人。下次请不要让我等太久。", source: "human" },
      ],
    },
  ],
  routeMap: {
    layoutDirection: "top-down",
    nodes: [
      {
        id: "route_return",
        kind: "start",
        title: "01 · 午后的归来",
        sceneId: "scene_return",
        x: 330,
        y: 70,
        replayable: true,
        color: "#6777ba",
      },
      {
        id: "route_teatime",
        kind: "scene",
        title: "02 · 茶会开始",
        sceneId: "scene_teatime",
        x: 330,
        y: 260,
        replayable: true,
        color: "#8d77b5",
      },
      {
        id: "route_questions",
        kind: "scene",
        title: "03 · 没说出口的问题",
        sceneId: "scene_questions",
        x: 330,
        y: 450,
        replayable: true,
        color: "#6f9b91",
      },
      {
        id: "route_protest",
        kind: "scene",
        title: "04 · 小小的抗议",
        sceneId: "scene_protest",
        x: 330,
        y: 640,
        replayable: true,
        color: "#c0808c",
      },
      {
        id: "route_bookmark",
        kind: "ending",
        title: "05 · 留给明天的书签",
        sceneId: "scene_bookmark",
        x: 330,
        y: 830,
        replayable: true,
        color: "#b78b55",
      },
    ],
    edges: [
      {
        id: "edge_return_teatime",
        source: "route_return",
        target: "route_teatime",
        label: "在窗边坐下",
      },
      {
        id: "edge_teatime_questions",
        source: "route_teatime",
        target: "route_questions",
        label: "谈起近况",
      },
      {
        id: "edge_questions_protest",
        source: "route_questions",
        target: "route_protest",
        label: "作出约定",
      },
      {
        id: "edge_protest_bookmark",
        source: "route_protest",
        target: "route_bookmark",
        label: "结束茶会",
      },
    ],
  },
  endings: [
    {
      id: "ending_bookmark",
      name: "留给明天的书签",
      kind: "normal",
      routeNodeId: "route_bookmark",
      sceneId: "scene_bookmark",
    },
  ],
  savePoints: [],
  aiConfigs: [],
};
