import generated from "./generatedAcceptance.json";
import { parseStoryProject } from "./schema";

/**
 * This project is generated by scripts/generate-ai-acceptance.ts through the
 * same public AI tool functions exposed by the editor. The JSON artifact and
 * tool-call transcript are committed so provenance can be inspected.
 */
export const generatedAcceptanceProject = parseStoryProject(generated);
