import generated from "./generatedAcceptance.json";
import { parseStoryProject } from "./schema";

/**
 * Generated by scripts/generate-ai-acceptance.ts through the same public AI
 * tools exposed by the editor. The JSON and call transcript are committed so
 * the production workflow remains independently auditable.
 */
export const generatedAcceptanceProject = parseStoryProject(generated);
