import type { StoryProject } from "./types";

const createdAt = "2026-08-20T12:00:00.000Z";

export const maidMotionProject: StoryProject = {
  schemaVersion: "1.0.0",
  id: "project_maid_motion_mvp",
  title: "女仆姬 · 动态立绘演出样章",
  slug: "maid-princess-motion-mvp",
  version: "1.0.0",
  description: "同一角色的两套立绘、独立眼嘴图层、自然眨眼、语音口型与句中姿势切换。",
  locale: "ja-JP",
  createdAt,
  updatedAt: createdAt,
  settings: {
    startSceneId: "scene_mai_motion",
    defaultMode: "adv",
    webgalVersion: "4.6.2",
    sharedEngineUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-BuN51U1e.js",
    sharedEngineCssUrl: "https://cdn.jsdelivr.net/npm/webgal-engine@4.6.2/dist/assets/index-Dch1g2w9.css",
    blogBridge: {
      enabled: false,
      allowedOrigins: [],
      channel: "gal-blog-game",
      timeoutMs: 20000,
      capabilities: [],
    },
  },
  chapters: [{
    id: "chapter_mai_mvp",
    name: "动态立绘 MVP",
    order: 0,
    description: "已验收的动态女仆立绘运行流程。",
    sceneIds: ["scene_mai_motion"],
  }],
  assets: [
    {
      id: "fig_mai_welcome",
      kind: "expression",
      name: "女仆姬 · 迎接姿势",
      path: "face-motion-demo/expressions/welcome-base.png",
      aliases: ["迎接", "正面", "welcome"],
      mimeType: "image/png",
      metadata: {
        figureShot: "waist",
        figureDefaultPosition: "center",
        figureDefaultX: 0,
        figureDefaultY: 0,
        figureDefaultScale: 1.48,
        sourceWidth: 1024,
        sourceHeight: 1536,
        semanticReady: true,
        bundled: true,
        layeredRuntime: true,
      },
    },
    {
      id: "fig_mai_guide",
      kind: "expression",
      name: "女仆姬 · 说明手势",
      path: "face-motion-demo/expressions/guide-base.png",
      aliases: ["说明", "侧身", "guide"],
      mimeType: "image/png",
      metadata: {
        figureShot: "waist",
        figureDefaultPosition: "center",
        figureDefaultX: 0,
        figureDefaultY: 0,
        figureDefaultScale: 1.48,
        sourceWidth: 1024,
        sourceHeight: 1536,
        semanticReady: true,
        bundled: true,
        layeredRuntime: true,
      },
    },
    {
      id: "voice_mai_mvp",
      kind: "voice",
      name: "Mai · MVP 台词",
      path: "face-motion-demo/voice.mp3",
      aliases: ["Mai语音", "测试语音"],
      mimeType: "audio/mpeg",
      metadata: { durationMs: 12800, bundled: true, mouthTimelinePath: "face-motion-demo/mouth-timeline.json" },
    },
  ],
  characters: [{
    id: "char_mai",
    name: "Mai",
    displayName: "Mai",
    aliases: ["女仆姬", "maid princess"],
    color: "#dfb46f",
    description: "动态立绘 MVP 的女仆角色。",
    persona: "温柔、略带歉意，说话时动作克制自然。",
    defaultExpressionId: "expr_mai_welcome",
    expressions: [
      {
        id: "expr_mai_welcome",
        name: "迎接姿势",
        assetId: "fig_mai_welcome",
        aliases: ["迎接", "正面"],
        tags: ["default", "calm", "layered-motion"],
        facialMotion: { manifestPath: "face-motion-demo/manifest.json", expressionId: "welcome" },
      },
      {
        id: "expr_mai_guide",
        name: "说明手势",
        assetId: "fig_mai_guide",
        aliases: ["说明", "侧身"],
        tags: ["guide", "layered-motion"],
        facialMotion: { manifestPath: "face-motion-demo/manifest.json", expressionId: "guide" },
      },
    ],
  }],
  variables: [],
  records: [],
  scenes: [{
    id: "scene_mai_motion",
    chapterId: "chapter_mai_mvp",
    name: "01 · 一句话动态演出",
    slug: "mai-motion-demo",
    summary: "Mai 先以迎接姿势说话，句中自然切换为说明手势。",
    aiContext: "只使用已登记的两套 Mai 立绘。角色始终居中半身构图；低强度自然入场、句中柔和换姿势，避免震屏和反复弹跳。",
    mode: "adv",
    tags: ["mvp", "layered-face-motion", "voice-sync"],
    entryStage: {
      figures: [{
        characterId: "char_mai",
        expressionId: "expr_mai_welcome",
        position: "center",
        transform: { x: 0, y: 0, scale: 1.48, rotation: 0, alpha: 1, zIndex: 1 },
      }],
    },
    blocks: [
      {
        id: "mai_enter",
        type: "stage",
        action: "enter-character",
        characterId: "char_mai",
        expressionId: "expr_mai_welcome",
        position: "center",
        transform: { x: 0, y: 0, scale: 1.48, rotation: 0, alpha: 1, zIndex: 1 },
        transition: { name: "enter", durationMs: 420, easing: "easeOut" },
        source: "system",
      },
      {
        id: "mai_mvp_line",
        type: "dialogue",
        characterId: "char_mai",
        expressionId: "expr_mai_welcome",
        voiceAssetId: "voice_mai_mvp",
        position: "center",
        transform: { x: 0, y: 0, scale: 1.48, rotation: 0, alpha: 1, zIndex: 1 },
        text: "あっ、ごめん……でも、ちゃんと説明するからね！",
        figureAnimation: { mouthSync: "on", blink: "dynamic" },
        source: "human",
      },
    ],
    staging: {
      enabled: true,
      revision: 1,
      cues: [
        { id: "cue_mai_enter", blockId: "mai_mvp_line", intent: "enter", targetCharacterId: "char_mai", timing: "before-line", intensity: "low", reason: "scene-entry", source: "system" },
        { id: "cue_mai_swap", blockId: "mai_mvp_line", intent: "pose-change", targetCharacterId: "char_mai", timing: "during-line", intensity: "low", reason: "emotional-turn", expressionId: "expr_mai_guide", voiceTimeMs: 6200, source: "system" },
        { id: "cue_mai_lean", blockId: "mai_mvp_line", intent: "micro-emphasis", targetCharacterId: "char_mai", timing: "during-line", intensity: "low", reason: "explicit-physical-action", voiceTimeMs: 7600, source: "system" },
        { id: "cue_mai_settle", blockId: "mai_mvp_line", intent: "hold", targetCharacterId: "char_mai", timing: "after-line", intensity: "low", source: "system" },
      ],
    },
  }],
  routeMap: {
    layoutDirection: "top-down",
    nodes: [{ id: "route_mai_start", kind: "start", title: "一句话动态演出", sceneId: "scene_mai_motion", x: 320, y: 80, replayable: true, color: "#c79258" }],
    edges: [],
  },
  endings: [],
  savePoints: [],
  aiConfigs: [],
};
